### ISSUE TITLE
[BUG] Unable to Deploy nginx-proxy-manager

### ISSUE THREAD

**Issue by schmittg25** [Qballjos/portainer_templates#27]
nginx-proxy-manager Won't Deploy. Get error message "Failure No Such image: jlesage/nginz-proxy-manager:latest"
As per the developer (https://nginxproxymanager.com/#quick-setup) it should be image: 'jc21/nginx-proxy-manager:latest'

**Comment by Qballjos** [comment]
Thank you for the report I have fixed the issue

**Comment by schmittg25** [comment]
It still won't deploy on a fresh install of portainer.io Now I am getting "Failure No Such image: jc21/nginx-proxy-manager:latest"

**Comment by Qballjos** [comment]
Sorry just tested it here but al seems fine.. maybe you have another issue perhaps OS/ARCH not supported?

I have added the sqlite option in the config and changed the data path according the new standards
